# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_version "2.32.1"

default_platform :ios

platform :ios do
  before_all do
    carthage
  end

  desc "Run all tests"
  lane :test do 
    scan
  end

  lane :icon_badge do
    add_badge(dark: true)
  end

  after_all do |lane|
    # slack(
    # message: "Successfully deployed new App Update"
    #)
  end

  error do |lane, exception|
    # slack(
    # message: exception.message, 
    # success: false 
    #)
  end
end